notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    username: 'drone'
    channel: '#miuras_gomibako'
    on_started: false
    on_success: true
    on_failure: true
